POST http://localhost:3000/api/video
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="video"; filename="sample.mp4"
Content-Type: video/mp4

< ./sample.mp4

--boundary--
